name: CI Cache Example

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: prime-cache-f6816b9
        id: prime-cache-f6816b9
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-f6816b9
      - name: Show cache result
        run: echo Cache hit: ${{ steps.prime-cache-f6816b9.outputs.cache-hit }}
